{{- include "invidious.init-defaults" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "invidious.fullname" . }}
  labels:
    {{- include "invidious.labels" . | nindent 4 }}
stringData:
  INVIDIOUS_CONFIG: |
    {{- toYaml .Values.config | nindent 4 }}
    {{- if .Values.companion.enabled }}
    invidious_companion_key: {{ .Values.companion.key }}
    {{- end }}